### ISSUE TITLE
Is it possible to move created file inside folder by folder id? Or Can we create spreadsheet directly inside folder by folder ID?

### ISSUE THREAD

**Issue by pankajthakur007** [googleworkspace/php-samples#83]
Is it possible to move created file inside folder by folder id? Or Can we create spreadsheet directly inside folder by folder ID?

**Comment by sqrrrl** [comment]
In the future, for general how-to advice, please use StackOverflow.

To answer your question, yes, you can move files to a parent folder if you know the folder ID. See https://developers.google.com/drive/api/v3/folder?hl=en for details (no PHP samples on that page, but shows the general approach that you can adapt.)
